### ISSUE TITLE
Requirements.

### ISSUE THREAD

**Issue by SeiZzzzz** [OllieBoyne/FOUND#1]
py-fbx==0.1.1 is depending on sip==4.19.7.
![image](https://github.com/OllieBoyne/FOUND/assets/78425132/d7fe07e3-1f16-4d2a-b112-51533eb26a2a)
v4 kinda outdated.

**Comment by OllieBoyne** [comment]
Thanks for this - I've simply removed `py-fbx` as a requirement.
