### ISSUE TITLE
Can i use collab?

### ISSUE THREAD

**Issue by SeiZzzzz** [OllieBoyne/FOUND#2]
How tf can i use it in de Google Collab or elsewhere.
If its not ever installed reqs with switched to 3.9 py version.
![image](https://github.com/OllieBoyne/FOUND/assets/78425132/c2f486ea-08f3-4af4-bba4-dab7729815a4)
Or its only collab platform error?
![image](https://github.com/OllieBoyne/FOUND/assets/78425132/2fcc672a-acab-430e-8bd1-8596063f58bd)

**Comment by OllieBoyne** [comment]
Hi, you'll have to address the specifics of installing `protobuf` on Google Collab, that's not really in the scope of this repo.

I can point you towards some PyTorch3D Google Collab examples where they seem to get it working: https://pytorch3d.org/tutorials/deform_source_mesh_to_target_mesh
