### ISSUE TITLE
Mismatch Between Dataset Keypoints and Paper Keypoints

### ISSUE THREAD

**Issue by OPAYA** [OllieBoyne/FOUND#6]
Hi!

I downloaded the provided dataset to train a keypoint prediction model. The dataset contains 8 keypoints, but the paper mentions a total of 12 keypoints. Is there something I might have missed or a part that I need to calculate a new?

The following keypoints are missing: “lower heel”, “arch1”, “arch2”, “arch3”.

Thank you

**Comment by OllieBoyne** [comment]
Hi,

The 12 keypoint version of the dataset was not released alongside SynFoot unfortunately. I have a smaller dataset (10k) that does have all 12 keypoints which I have included as a link below - hope this helps!

https://1drv.ms/f/s!AgX_CR94DLQeprNUPPpFj--JxzjhEw?e=pXODmq
