### ISSUE TITLE
Can You Tell Me the COLMAP Command Line Parameters?

### ISSUE THREAD

**Issue by OPAYA** [OllieBoyne/FOUND#7]
Hi!
Thank you for always responding so kindly.

I extracted features using COLMAP with your standard dataset and generated a new colmap.json file (after deleting the original colmap.json and regenerating it with COLMAP).

However, the loss is diverging and the optimization is not converging.

Am I using it incorrectly?

```bash
colmap feature_extractor \
    --database_path path/to/database.db \
    --image_path path/to/images

colmap exhaustive_matcher \
    --database_path path/to/database.db

mkdir path/to/sparse

colmap mapper \
    --database_path path/to/database.db \
    --image_path path/to/images \
    --output_path path/to/sparse

mkdir path/to/sparse_text

colmap model_converter \
    --input_path path/to/sparse/0 \
    --output_path path/to/sparse_text \
    --output_type TXT
```

**Comment by OllieBoyne** [comment]
Hi! Below are all the steps I use with any extra arguments I needed.

- `feature_extractor` - `ImageReader.single_camera = '1'`
- `exhaustive_matcher`
- `mapper` - `Mapper.ba_refine_focal_length = '1'`
- `image_undistorter` - `output_type = 'COLMAP'`
- `patch_match_stereo` - `workspace_format = 'COLMAP'`, `PatchMatchStereo.geom_consistency = '1'`
- `stereo_fusion` - `workspace_format = 'COLMAP'`, `input_type = 'geometric'`
- `poisson_mesher` - `PoissonMeshing.trim = '1'`

Hope this helps!

**Comment by OPAYA** [comment]
Thank you!

So, I need to convert the images.bin and cameras.bin files in the dense/sparse folder into a colmap.json file?

**Comment by OllieBoyne** [comment]
Yes. The scripts to read from COLMAP `.bin` files are provided in the COLMAP source code [here](https://github.com/colmap/colmap/blob/main/scripts/python/read_write_model.py)
