### ISSUE TITLE
I am curious about the COLMAP version.

### ISSUE THREAD

**Issue by OPAYA** [OllieBoyne/FOUND#8]
I am using the feature_extractor and mapper of COLMAP to extract images.txt and camera.txt. I’m using version 3.11, but it seems like the data in the colmap.json provided for testing is different. Could you let me know which version of COLMAP you used?

If possible, could you provide the code to create colmap.json from images?

Thank you!

**Comment by OllieBoyne** [comment]
Hi. COLMAP 3.8 was used for this project.

I am working on a script to convert a COLMAP reconstruction to the data format needed for FOUND, I will post here when it is released.

**Comment by OllieBoyne** [comment]
Regarding the second point, please see my answer [here](https://github.com/OllieBoyne/FOUND/issues/4#issuecomment-2315753989) #4
